import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:ventio/core/services/local_database_service.dart';
import 'package:ventio/data/app_store.dart';
import 'package:ventio/models/customer.dart';
import 'package:ventio/models/product.dart';
import 'package:ventio/models/sale_item.dart';
import 'package:ventio/models/supplier.dart';

int _envInt(String key, int fallback) {
  final raw = Platform.environment[key];
  if (raw == null || raw.trim().isEmpty) return fallback;
  return int.tryParse(raw.trim()) ?? fallback;
}

Map<String, String> _hostIdentitySeed() {
  final now = DateTime(2026, 1, 1).toIso8601String();
  return <String, String>{
    'app_identity_v1': jsonEncode(<String, dynamic>{
      'storeId': 'ST-STRESS',
      'branchId': 'BR-STRESS',
      'deviceId': 'DV-STRESS-HOST',
      'deviceName': 'Stress Test Host',
      'platform': 'windows',
      'deviceRole': 'host',
      'appRole': 'store',
      'syncMode': 'lanOnly',
      'createdAt': now,
      'updatedAt': now,
      'hostDeviceId': '',
      'cloudTenantId': '',
      'deviceToken': 'device_stress_host_token',
      'storeEpoch': 1,
      'recoveryKey': 'RK-STRESS-TEST-HOST',
    }),
  };
}

Future<AppStore> _readyStore() async {
  TestWidgetsFlutterBinding.ensureInitialized();
  SharedPreferences.setMockInitialValues(const <String, Object>{});
  LocalDatabaseService.useInMemoryStoreForTesting(_hostIdentitySeed());

  final store = AppStore();
  await store.initialize();
  await store.completeInitialAdminSetup(
    fullName: 'Admin',
    username: 'admin',
    password: 'AdminPass123',
  );
  return store;
}

Product _product(int i) {
  final price = 3.0 + (i % 500) / 10.0;
  final cost = price * 0.60;
  return Product(
    id: 'stress_product_$i',
    code: 'SKU-${i.toString().padLeft(6, '0')}',
    name: 'Stress Product ${i.toString().padLeft(6, '0')}',
    nameEn: 'Stress Product $i',
    nameAr: 'منتج اختبار $i',
    price: price,
    cost: cost,
    usdCost: cost,
    originalCost: cost,
    stock: 1000000,
    category: 'Category ${i % 20}',
    brand: 'Brand ${i % 50}',
    supplier: 'Supplier ${i % 500}',
    barcode: 'BC${i.toString().padLeft(12, '0')}',
    unit: 'pcs',
    lowStockThreshold: 5,
    trackStock: true,
  );
}

Customer _customer(int i) => Customer(
      id: 'stress_customer_$i',
      name: 'Stress Customer $i',
      phone: '70${i.toString().padLeft(6, '0')}',
      address: 'Stress Address $i',
    );

Supplier _supplier(int i) => Supplier(
      id: 'stress_supplier_$i',
      name: 'Stress Supplier $i',
      nameEn: 'Stress Supplier $i',
      nameAr: 'مورد اختبار $i',
      phone: '71${i.toString().padLeft(6, '0')}',
      address: 'Supplier Address $i',
      notes: 'Generated by stress test',
    );

void _log(String message) => stdout.writeln('[Ventio stress] $message');

void main() {
  test('synthetic launch stress test: catalog + sales + sync queue + backup roundtrip', () async {
    final productCount = _envInt('PRODUCTS', 1000);
    final saleCount = _envInt('SALES', 5000);
    final customerCount = _envInt('CUSTOMERS', 500);
    final supplierCount = _envInt('SUPPLIERS', 100);
    final maxItemsPerSale = max(1, _envInt('MAX_ITEMS_PER_SALE', 5));

    final store = await _readyStore();
    final random = Random(51);
    final totalWatch = Stopwatch()..start();

    _log('Seeding $supplierCount suppliers...');
    var watch = Stopwatch()..start();
    for (var i = 0; i < supplierCount; i++) {
      await store.addOrUpdateSupplier(_supplier(i));
    }
    _log('Suppliers done in ${watch.elapsedMilliseconds} ms');

    _log('Seeding $customerCount customers...');
    watch = Stopwatch()..start();
    for (var i = 0; i < customerCount; i++) {
      await store.addOrUpdateCustomer(_customer(i));
    }
    _log('Customers done in ${watch.elapsedMilliseconds} ms');

    _log('Seeding $productCount products...');
    watch = Stopwatch()..start();
    for (var i = 0; i < productCount; i++) {
      await store.addOrUpdateProduct(_product(i));
      if (i > 0 && i % 1000 == 0) _log('Products: $i/$productCount');
    }
    _log('Products done in ${watch.elapsedMilliseconds} ms');

    final products = store.products.toList();
    expect(products.length, productCount);

    final progressEvery = max(1, _envInt('PROGRESS_EVERY', 50));
    final slowMs = _envInt('SLOW_SALE_MS', 1000);
    final hardTimeoutSec = _envInt('SALE_TIMEOUT_SEC', 30);

    _log('Creating $saleCount sales... progressEvery=$progressEvery slowMs=$slowMs saleTimeout=${hardTimeoutSec}s');
    watch = Stopwatch()..start();
    var lastProgressAt = DateTime.now();
    var maxSaleMs = 0;
    var totalSaleMs = 0;
    var slowSales = 0;

    for (var i = 0; i < saleCount; i++) {
      final saleWatch = Stopwatch()..start();
      try {
        final itemCount = 1 + random.nextInt(maxItemsPerSale);
        final used = <String>{};
        final items = <SaleItem>[];

        while (items.length < itemCount) {
          final product = products[random.nextInt(products.length)];
          if (!used.add(product.id)) continue;
          final qty = 1 + random.nextInt(3);
          items.add(SaleItem(
            productId: product.id,
            productName: product.name,
            unitPrice: product.price,
            quantity: qty.toDouble(),
            unitName: product.unit,
            baseQuantity: qty.toDouble(),
            conversionToBase: 1,
            unitCost: product.usdCost,
          ));
        }

        await store.createSale(
          customerName: 'Stress Customer ${i % max(1, customerCount)}',
          items: items,
          paymentMethod: i.isEven ? 'Cash' : 'Card',
        ).timeout(Duration(seconds: hardTimeoutSec));
      } catch (error, stackTrace) {
        _log('FAILED at sale index=$i elapsedTotal=${watch.elapsed} salesCreated=${store.sales.length} products=${store.products.length} stockMovements=${store.stockMovements.length} pendingQueue=${store.pendingSyncQueueCount} pendingChanges=${store.pendingSyncChanges.length}');
        _log('ERROR: $error');
        stdout.writeln(stackTrace);
        rethrow;
      } finally {
        saleWatch.stop();
      }

      final ms = saleWatch.elapsedMilliseconds;
      totalSaleMs += ms;
      if (ms > maxSaleMs) maxSaleMs = ms;
      if (ms >= slowMs) {
        slowSales += 1;
        _log('SLOW sale=${i + 1}/$saleCount took=${ms}ms total=${watch.elapsed} sales=${store.sales.length} stockMovements=${store.stockMovements.length} pendingQueue=${store.pendingSyncQueueCount} pendingChanges=${store.pendingSyncChanges.length}');
      }

      if ((i + 1) % progressEvery == 0 || i == 0 || i + 1 == saleCount) {
        final avg = totalSaleMs / (i + 1);
        final now = DateTime.now();
        final sinceLast = now.difference(lastProgressAt).inMilliseconds;
        lastProgressAt = now;
        _log('Sales progress: ${i + 1}/$saleCount batchMs=$sinceLast avgSaleMs=${avg.toStringAsFixed(1)} maxSaleMs=$maxSaleMs slowSales=$slowSales total=${watch.elapsed} sales=${store.sales.length} stockMovements=${store.stockMovements.length} pendingQueue=${store.pendingSyncQueueCount} pendingChanges=${store.pendingSyncChanges.length}');
      }
    }
    _log('Sales done in ${watch.elapsedMilliseconds} ms avgSaleMs=${(totalSaleMs / max(1, saleCount)).toStringAsFixed(1)} maxSaleMs=$maxSaleMs slowSales=$slowSales');

    _log('Running assertions...');
    expect(store.sales.length, saleCount);
    expect(store.products.where((p) => p.stock < 0), isEmpty);
    expect(store.totalSalesAmount, greaterThan(0));
    expect(store.pendingSyncQueueCount, greaterThan(0));
    expect(store.pendingSyncChanges.length, greaterThanOrEqualTo(saleCount));

    _log('Exporting backup...');
    watch = Stopwatch()..start();
    final backup = store.exportBackupJson();
    final backupBytes = utf8.encode(backup).length;
    _log('Backup size: ${(backupBytes / 1024 / 1024).toStringAsFixed(2)} MB in ${watch.elapsedMilliseconds} ms');
    expect(store.validateBackupJson(backup).isValid, isTrue);

    _log('Resetting and importing backup...');
    watch = Stopwatch()..start();
    await store.resetBusinessData();
    await store.importBackupJson(backup);
    _log('Restore done in ${watch.elapsedMilliseconds} ms');

    expect(store.products.length, productCount);
    expect(store.sales.length, saleCount);
    expect(store.products.where((p) => p.stock < 0), isEmpty);

    totalWatch.stop();
    _log('DONE total=${totalWatch.elapsed} products=${store.products.length} sales=${store.sales.length} pendingQueue=${store.pendingSyncQueueCount} pendingChanges=${store.pendingSyncChanges.length}');
  }, timeout: const Timeout(Duration(minutes: 60)));
}
