class Expense {
  Expense({required this.id, required this.title, required this.category, required this.amount, required this.date, required this.notes, DateTime? createdAt, DateTime? updatedAt, this.deletedAt, this.deviceId = '', this.syncStatus = 'pending', this.storeId = '', this.branchId = '', this.version = 1, this.lastModifiedByDeviceId = ''}) : createdAt = createdAt ?? updatedAt ?? DateTime.fromMillisecondsSinceEpoch(0), updatedAt = updatedAt ?? createdAt ?? DateTime.fromMillisecondsSinceEpoch(0);
  final String id, title, category, notes, deviceId, syncStatus, storeId, branchId, lastModifiedByDeviceId;
  final double amount; final DateTime date, createdAt, updatedAt; final DateTime? deletedAt; final int version;
  bool get isDeleted => deletedAt != null;
  Expense copyWith({String? id, String? title, String? category, double? amount, DateTime? date, String? notes, DateTime? createdAt, DateTime? updatedAt, DateTime? deletedAt, bool clearDeletedAt = false, String? deviceId, String? syncStatus, String? storeId, String? branchId, int? version, String? lastModifiedByDeviceId}) => Expense(id: id ?? this.id, title: title ?? this.title, category: category ?? this.category, amount: amount ?? this.amount, date: date ?? this.date, notes: notes ?? this.notes, createdAt: createdAt ?? this.createdAt, updatedAt: updatedAt ?? this.updatedAt, deletedAt: clearDeletedAt ? null : (deletedAt ?? this.deletedAt), deviceId: deviceId ?? this.deviceId, syncStatus: syncStatus ?? this.syncStatus, storeId: storeId ?? this.storeId, branchId: branchId ?? this.branchId, version: version ?? this.version, lastModifiedByDeviceId: lastModifiedByDeviceId ?? this.lastModifiedByDeviceId);
  Map<String, dynamic> toJson() => {'id': id, 'title': title, 'category': category, 'amount': amount, 'date': date.toIso8601String(), 'notes': notes, 'createdAt': createdAt.toIso8601String(), 'updatedAt': updatedAt.toIso8601String(), 'deletedAt': deletedAt?.toIso8601String(), 'deviceId': deviceId, 'syncStatus': syncStatus, 'storeId': storeId, 'branchId': branchId, 'version': version, 'lastModifiedByDeviceId': lastModifiedByDeviceId};
  factory Expense.fromJson(Map<String, dynamic> json) { final updated = DateTime.tryParse(json['updatedAt'] as String? ?? '') ?? DateTime.now(); return Expense(id: json['id'] as String, title: json['title'] as String? ?? '', category: json['category'] as String? ?? '', amount: (json['amount'] as num? ?? 0).toDouble(), date: DateTime.tryParse(json['date'] as String? ?? '') ?? DateTime.now(), notes: json['notes'] as String? ?? '', createdAt: DateTime.tryParse(json['createdAt'] as String? ?? '') ?? updated, updatedAt: updated, deletedAt: DateTime.tryParse(json['deletedAt'] as String? ?? ''), deviceId: json['deviceId'] as String? ?? '', syncStatus: json['syncStatus'] as String? ?? 'synced', storeId: json['storeId'] as String? ?? '', branchId: json['branchId'] as String? ?? '', version: (json['version'] as num? ?? 1).toInt(), lastModifiedByDeviceId: json['lastModifiedByDeviceId'] as String? ?? json['deviceId'] as String? ?? ''); }
}
