class StockMovement {
  StockMovement({
    required this.id,
    required this.productId,
    required this.productName,
    required this.type,
    required this.quantity,
    required this.date,
    this.referenceId = '',
    this.referenceNo = '',
    this.reason = '',
    this.adjustmentCategory = '',
    this.notes = '',
    this.evidenceRef = '',
    this.warehouseId = 'main',
    this.warehouseName = 'Main warehouse',
    this.movementGroupId = '',
    this.documentLineId = '',
    this.sourceMovementId = '',
    this.reversalOfMovementId = '',
    this.idempotencyKey = '',
    this.unitCost = 0,
    DateTime? createdAt,
    DateTime? updatedAt,
    this.deviceId = '',
    this.syncStatus = 'pending',
    this.storeId = '',
    this.branchId = '',
    this.version = 1,
    this.lastModifiedByDeviceId = '',
    this.reviewedAt,
    this.reviewedBy = '',
    this.reviewNote = '',
  })  : createdAt = createdAt ?? updatedAt ?? date,
        updatedAt = updatedAt ?? createdAt ?? date;

  final String id, productId, productName, type, referenceId, referenceNo, reason;
  final String adjustmentCategory, notes, evidenceRef, warehouseId, warehouseName;
  final String movementGroupId, documentLineId, sourceMovementId;
  final String reversalOfMovementId, idempotencyKey;
  final double quantity;
  final double unitCost;
  final DateTime date, createdAt, updatedAt;
  final String deviceId, syncStatus, storeId, branchId, lastModifiedByDeviceId;
  final DateTime? reviewedAt;
  final String reviewedBy, reviewNote;
  final int version;

  bool get isReviewed => reviewedAt != null;

  double get value => quantity.abs() * unitCost;

  StockMovement copyWith({
    String? id,
    String? productId,
    String? productName,
    String? type,
    double? quantity,
    DateTime? date,
    String? referenceId,
    String? referenceNo,
    String? reason,
    String? adjustmentCategory,
    String? notes,
    String? evidenceRef,
    String? warehouseId,
    String? warehouseName,
    String? movementGroupId,
    String? documentLineId,
    String? sourceMovementId,
    String? reversalOfMovementId,
    String? idempotencyKey,
    double? unitCost,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? deviceId,
    String? syncStatus,
    String? storeId,
    String? branchId,
    int? version,
    String? lastModifiedByDeviceId,
    DateTime? reviewedAt,
    bool clearReviewedAt = false,
    String? reviewedBy,
    String? reviewNote,
  }) =>
      StockMovement(
        id: id ?? this.id,
        productId: productId ?? this.productId,
        productName: productName ?? this.productName,
        type: type ?? this.type,
        quantity: quantity ?? this.quantity,
        date: date ?? this.date,
        referenceId: referenceId ?? this.referenceId,
        referenceNo: referenceNo ?? this.referenceNo,
        reason: reason ?? this.reason,
        adjustmentCategory: adjustmentCategory ?? this.adjustmentCategory,
        notes: notes ?? this.notes,
        evidenceRef: evidenceRef ?? this.evidenceRef,
        warehouseId: warehouseId ?? this.warehouseId,
        warehouseName: warehouseName ?? this.warehouseName,
        movementGroupId: movementGroupId ?? this.movementGroupId,
        documentLineId: documentLineId ?? this.documentLineId,
        sourceMovementId: sourceMovementId ?? this.sourceMovementId,
        reversalOfMovementId:
            reversalOfMovementId ?? this.reversalOfMovementId,
        idempotencyKey: idempotencyKey ?? this.idempotencyKey,
        unitCost: unitCost ?? this.unitCost,
        createdAt: createdAt ?? this.createdAt,
        updatedAt: updatedAt ?? this.updatedAt,
        deviceId: deviceId ?? this.deviceId,
        syncStatus: syncStatus ?? this.syncStatus,
        storeId: storeId ?? this.storeId,
        branchId: branchId ?? this.branchId,
        version: version ?? this.version,
        lastModifiedByDeviceId: lastModifiedByDeviceId ?? this.lastModifiedByDeviceId,
        reviewedAt: clearReviewedAt ? null : (reviewedAt ?? this.reviewedAt),
        reviewedBy: reviewedBy ?? this.reviewedBy,
        reviewNote: reviewNote ?? this.reviewNote,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'productId': productId,
        'productName': productName,
        'type': type,
        'quantity': quantity,
        'date': date.toIso8601String(),
        'referenceId': referenceId,
        'referenceNo': referenceNo,
        'reason': reason,
        'adjustmentCategory': adjustmentCategory,
        'notes': notes,
        'evidenceRef': evidenceRef,
        'warehouseId': warehouseId,
        'warehouseName': warehouseName,
        'movementGroupId': movementGroupId,
        'documentLineId': documentLineId,
        'sourceMovementId': sourceMovementId,
        'reversalOfMovementId': reversalOfMovementId,
        'idempotencyKey': idempotencyKey,
        'unitCost': unitCost,
        'createdAt': createdAt.toIso8601String(),
        'updatedAt': updatedAt.toIso8601String(),
        'deviceId': deviceId,
        'syncStatus': syncStatus,
        'storeId': storeId,
        'branchId': branchId,
        'version': version,
        'lastModifiedByDeviceId': lastModifiedByDeviceId,
        'reviewedAt': reviewedAt?.toIso8601String(),
        'reviewedBy': reviewedBy,
        'reviewNote': reviewNote,
      };

  factory StockMovement.fromJson(Map<String, dynamic> json) {
    final date = DateTime.tryParse(json['date']?.toString() ?? json['createdAt']?.toString() ?? '') ?? DateTime.now();
    return StockMovement(
      id: json['id']?.toString() ?? '${json['referenceId'] ?? ''}-${json['productId'] ?? ''}-${json['type'] ?? ''}',
      productId: json['productId']?.toString() ?? '',
      productName: json['productName']?.toString() ?? '',
      type: json['type']?.toString() ?? 'adjustment',
      quantity: (json['quantity'] as num? ?? 0).toDouble(),
      date: date,
      referenceId: json['referenceId']?.toString() ?? json['saleId']?.toString() ?? json['purchaseId']?.toString() ?? '',
      referenceNo: json['referenceNo']?.toString() ?? '',
      reason: json['reason']?.toString() ?? '',
      adjustmentCategory: json['adjustmentCategory']?.toString() ?? json['category']?.toString() ?? '',
      notes: json['notes']?.toString() ?? '',
      evidenceRef: json['evidenceRef']?.toString() ?? '',
      warehouseId: json['warehouseId']?.toString() ?? 'main',
      warehouseName: json['warehouseName']?.toString() ?? 'Main warehouse',
      movementGroupId: json['movementGroupId']?.toString() ?? '',
      documentLineId: json['documentLineId']?.toString() ?? '',
      sourceMovementId: json['sourceMovementId']?.toString() ?? '',
      reversalOfMovementId: json['reversalOfMovementId']?.toString() ?? '',
      idempotencyKey: json['idempotencyKey']?.toString() ?? '',
      unitCost: (json['unitCost'] as num? ?? 0).toDouble(),
      createdAt: DateTime.tryParse(json['createdAt']?.toString() ?? '') ?? date,
      updatedAt: DateTime.tryParse(json['updatedAt']?.toString() ?? '') ?? date,
      deviceId: json['deviceId']?.toString() ?? '',
      syncStatus: json['syncStatus']?.toString() ?? 'synced',
      storeId: json['storeId']?.toString() ?? '',
      branchId: json['branchId']?.toString() ?? '',
      version: (json['version'] as num? ?? 1).toInt(),
      lastModifiedByDeviceId: json['lastModifiedByDeviceId']?.toString() ?? json['deviceId']?.toString() ?? '',
      reviewedAt: DateTime.tryParse(json['reviewedAt']?.toString() ?? ''),
      reviewedBy: json['reviewedBy']?.toString() ?? '',
      reviewNote: json['reviewNote']?.toString() ?? '',
    );
  }
}
