enum StressLabCoverageState {
  full,
  partial,
  missing,
}

enum StressLabScenarioKind {
  commerce,
  inventory,
  accounting,
  reports,
  settings,
  sync,
  maintenance,
  admin,
  system,
  tooling,
}

class StressLabCoverageEntry {
  const StressLabCoverageEntry({
    required this.pageKey,
    required this.label,
    required this.state,
    required this.kind,
    required this.notes,
    this.requiredRole = '',
    this.isToolingPage = false,
    this.seedsData = false,
    this.drivesUi = false,
    this.assertsState = false,
  });

  final String pageKey;
  final String label;
  final StressLabCoverageState state;
  final StressLabScenarioKind kind;
  final String notes;
  final String requiredRole;
  final bool isToolingPage;
  final bool seedsData;
  final bool drivesUi;
  final bool assertsState;
}

const List<StressLabCoverageEntry> stressLabCoverageManifest =
    <StressLabCoverageEntry>[
  StressLabCoverageEntry(
    pageKey: 'LoginGatePage',
    label: 'Login gate',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.system,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stress Lab now covers online login, registration, recovery gating, and cache routing for the login surface.',
  ),
  StressLabCoverageEntry(
    pageKey: 'MainShell',
    label: 'Main shell',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.system,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stress Lab now covers shell identity readiness, nav permissions, and admin/store routing branches.',
  ),
  StressLabCoverageEntry(
    pageKey: 'DashboardPage',
    label: 'Dashboard',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.commerce,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Generated data and readiness checks now exercise the dashboard module end-to-end.',
  ),
  StressLabCoverageEntry(
    pageKey: 'ProductsPage',
    label: 'Products',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.commerce,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Seed, mutations, pressure checks, and assertions cover the module end-to-end.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'CustomersPage',
    label: 'Customers',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.commerce,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Seed, mutations, pressure checks, and assertions cover the module end-to-end.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'SuppliersPage',
    label: 'Suppliers',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.commerce,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Seed, mutations, pressure checks, and assertions cover the module end-to-end.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'SalesPage',
    label: 'Sales',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.commerce,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Sales creation, cancellation checks, stock references, and accounting assertions are covered.',
    requiredRole: 'cashier',
  ),
  StressLabCoverageEntry(
    pageKey: 'QuotationsPage',
    label: 'Quotations',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.commerce,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stress Lab now creates, converts, and validates quotation flows together with downstream sales data.',
    requiredRole: 'cashier',
  ),
  StressLabCoverageEntry(
    pageKey: 'DeliveryNotesPage',
    label: 'Delivery notes',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.commerce,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stress Lab now creates, delivers, and validates delivery note linkage and reporting readiness.',
    requiredRole: 'cashier',
  ),
  StressLabCoverageEntry(
    pageKey: 'PurchasesPage',
    label: 'Purchases',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.commerce,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Purchase creation, receiving, stock links, and accounting checks are covered.',
    requiredRole: 'warehouse',
  ),
  StressLabCoverageEntry(
    pageKey: 'ExpensesPage',
    label: 'Expenses',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.accounting,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Expense creation, posting, cancellation, and journal checks are covered.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'AccountingPage',
    label: 'Accounting',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.accounting,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stress Lab now covers journal posting, trial balance, cash drawer, and accounting assertions end-to-end.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'InventoryPage',
    label: 'Inventory',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.inventory,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stock adjustments, transfers, counts, and integrity checks are covered.',
    requiredRole: 'warehouse',
  ),
  StressLabCoverageEntry(
    pageKey: 'ManufacturingPage',
    label: 'Manufacturing',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.inventory,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stress Lab now creates BOMs and completed manufacturing orders and validates the stock impact.',
    requiredRole: 'warehouse',
  ),
  StressLabCoverageEntry(
    pageKey: 'ReportsPage',
    label: 'Reports',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.reports,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stress Lab now ensures report-ready sources exist for financial, operational, and inventory reporting.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'MaintenancePage',
    label: 'Maintenance',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.maintenance,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Health checks, diagnostics, and repair flows are now exercised through the maintenance surface.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'DatabasePage',
    label: 'Database',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.maintenance,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Database inspection, SQL validation, and export helpers are now covered.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'SettingsPage',
    label: 'Settings',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.settings,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Core settings data, persistence services, and major subpages are now covered.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'AdminSubscribersPage',
    label: 'Admin subscribers',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.admin,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stress Lab now covers subscriber loading, filtering, edit, and delete flows through the service layer.',
    requiredRole: 'admin',
  ),
  StressLabCoverageEntry(
    pageKey: 'StoreAccountDashboardPage',
    label: 'Store account dashboard',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.admin,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Stress Lab now covers login/cache routing, password changes, owner profile updates, and recovery gating.',
    requiredRole: 'admin',
  ),
  StressLabCoverageEntry(
    pageKey: 'PlatformAdminDashboardPage',
    label: 'Platform admin dashboard',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.admin,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Platform admin routing and subscriber management are covered through the admin service probes.',
    requiredRole: 'admin',
  ),
  StressLabCoverageEntry(
    pageKey: 'DiagnosticsPage',
    label: 'Diagnostics',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.system,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Diagnostics now builds health reports, log snapshots, and coverage assertions end-to-end.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'SyncSetupPage',
    label: 'Sync setup',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.sync,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Sync settings persistence and pairing probes now cover the setup surface end-to-end.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'UsersPermissionsPage',
    label: 'Users permissions',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.settings,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Roles, demo users, and role mutation flows are now covered end-to-end.',
    requiredRole: 'manager',
  ),
  StressLabCoverageEntry(
    pageKey: 'BarcodeScannerPage',
    label: 'Barcode scanner',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.system,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Scanner support detection and fallback behavior are now covered as part of the device tools journey.',
    requiredRole: 'cashier',
  ),
  StressLabCoverageEntry(
    pageKey: 'StressLabPage',
    label: 'Stress lab',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.tooling,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'This is the tooling page itself; the runner is present, but it is not a business module.',
    isToolingPage: true,
  ),
  StressLabCoverageEntry(
    pageKey: '_NoAccessPage',
    label: 'No access',
    state: StressLabCoverageState.full,
    kind: StressLabScenarioKind.tooling,
    seedsData: true,
    drivesUi: true,
    assertsState: true,
    notes: 'Access-denied fallback coverage is now exercised through the protected surface probes.',
    isToolingPage: true,
  ),
];

const List<({String key, String label})> stressLabRegisteredPages =
    <({String key, String label})>[
  (key: 'LoginGatePage', label: 'Login gate'),
  (key: 'MainShell', label: 'Main shell'),
  (key: 'DashboardPage', label: 'Dashboard'),
  (key: 'ProductsPage', label: 'Products'),
  (key: 'CustomersPage', label: 'Customers'),
  (key: 'SuppliersPage', label: 'Suppliers'),
  (key: 'SalesPage', label: 'Sales'),
  (key: 'QuotationsPage', label: 'Quotations'),
  (key: 'DeliveryNotesPage', label: 'Delivery notes'),
  (key: 'PurchasesPage', label: 'Purchases'),
  (key: 'ExpensesPage', label: 'Expenses'),
  (key: 'AccountingPage', label: 'Accounting'),
  (key: 'InventoryPage', label: 'Inventory'),
  (key: 'ManufacturingPage', label: 'Manufacturing'),
  (key: 'ReportsPage', label: 'Reports'),
  (key: 'MaintenancePage', label: 'Maintenance'),
  (key: 'DatabasePage', label: 'Database'),
  (key: 'SettingsPage', label: 'Settings'),
  (key: 'AdminSubscribersPage', label: 'Admin subscribers'),
  (key: 'StoreAccountDashboardPage', label: 'Store account dashboard'),
  (key: 'PlatformAdminDashboardPage', label: 'Platform admin dashboard'),
  (key: 'DiagnosticsPage', label: 'Diagnostics'),
  (key: 'SyncSetupPage', label: 'Sync setup'),
  (key: 'UsersPermissionsPage', label: 'Users permissions'),
  (key: 'BarcodeScannerPage', label: 'Barcode scanner'),
  (key: 'StressLabPage', label: 'Stress lab'),
  (key: '_NoAccessPage', label: 'No access'),
];

Map<StressLabCoverageState, int> stressLabCoverageCounts() {
  final counts = <StressLabCoverageState, int>{
    StressLabCoverageState.full: 0,
    StressLabCoverageState.partial: 0,
    StressLabCoverageState.missing: 0,
  };
  for (final entry in stressLabCoverageManifest) {
    counts[entry.state] = counts[entry.state]! + 1;
  }
  return counts;
}

Map<StressLabScenarioKind, int> stressLabScenarioCounts() {
  final counts = <StressLabScenarioKind, int>{
    for (final kind in StressLabScenarioKind.values) kind: 0,
  };
  for (final entry in stressLabCoverageManifest) {
    counts[entry.kind] = counts[entry.kind]! + 1;
  }
  return counts;
}
